### ISSUE TITLE
How to change attributes of text already printed

### ISSUE THREAD

**Issue by mare-imbrium** [dylanaraps/writing-a-tui-in-bash#3]
Thanks for the excellent work. This is a query, can't find any answers on the net.

In ncurses we have `mvchgat` by which we can change the attributes of text already printed. For example, i can go to a line and underline some characters. 

In bash, I am only able to find how I can set a background/attribute and *then* print characters.

Do you know of any way of implementing `chgat` in a bash script ?

Thanks.

**Comment by dylanaraps** [comment]
You have to overwrite the text yourself. There's no way to update existing output. From bash you have no access to the contents of the terminal (*only what you know from printing it*). I don't know about writing a manual TUI in C or a lower level language.
